package com.exapps.velox.core.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Phase 3 / Wave 3 / Round 2 — Milestone 5 / 6. Two new tables
 * for the audio-analysis module.
 *
 *  - [TrackIntroOutroEntity] holds silence-run results (intro /
 *    outro skip candidates). One row per (mediaItemId, kind).
 *  - [TrackChapterEntity] holds auto-generated chapter boundaries.
 *    Many rows per mediaItemId; ordered by `index`.
 *
 * Both are added in a single schema migration (3 → 4) so the
 * upgrade is atomic — a half-migrated DB with only one of the
 * two tables would crash the analyzer the first time it ran.
 */

@Entity(
    tableName = "track_intro_outro",
    primaryKeys = ["mediaItemId", "kind"],
    foreignKeys = [
        ForeignKey(
            entity = MediaItemEntity::class,
            parentColumns = ["id"],
            childColumns = ["mediaItemId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("mediaItemId")],
)
data class TrackIntroOutroEntity(
    @ColumnInfo(name = "mediaItemId") val mediaItemId: Long,
    /** 0 = INTRO, 1 = OUTRO. Persisted as int to match Room's
     *  primary-key composite-type constraints. */
    @ColumnInfo(name = "kind") val kind: Int,
    @ColumnInfo(name = "startMs") val startMs: Long,
    @ColumnInfo(name = "endMs") val endMs: Long,
)

@Entity(
    tableName = "track_chapters",
    primaryKeys = ["mediaItemId", "index"],
    foreignKeys = [
        ForeignKey(
            entity = MediaItemEntity::class,
            parentColumns = ["id"],
            childColumns = ["mediaItemId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("mediaItemId")],
)
data class TrackChapterEntity(
    @ColumnInfo(name = "mediaItemId") val mediaItemId: Long,
    @ColumnInfo(name = "index") val index: Int,
    @ColumnInfo(name = "positionMs") val positionMs: Long,
    /** True for [com.exapps.velox.core.audioanalysis.ChapterDetector] output;
     *  false for sidecar `.chapters.txt` or embedded chapters.
     *  Round 2 only writes true values; the column exists so a
     *  future "embedded chapter import" doesn't require a
     *  schema bump. */
    @ColumnInfo(name = "autoGenerated") val autoGenerated: Boolean,
)
