package com.exapps.velox.core.domain.audio

/**
 * Phase 3 / Wave 3 / Round 2 — Audio analysis. The persisted
 * result of running [com.exapps.velox.core.audioanalysis.TrackAnalyzer]
 * on a media item.
 *
 * Stored in a new Room table (`track_intro_outro`) keyed by
 * `(mediaItemId, kind)`. The kind discriminator exists so the
 * same row shape can carry both intro and outro detections
 * without a second table; round-1 of detection only writes INTRO
 * rows, but the chapter milestone writes CHAPTER rows in a
 * separate table (`track_chapters`).
 */
data class IntroOutro(
    val mediaItemId: Long,
    val kind: IntroOutroKind,
    /** Start of the silence run, in milliseconds from track start. */
    val startMs: Long,
    /** End of the silence run, in milliseconds from track start. */
    val endMs: Long,
)

enum class IntroOutroKind { INTRO, OUTRO }

/**
 * Phase 3 / Wave 3 / Round 2 — Chapter detection. A single
 * chapter boundary produced by the [com.exapps.velox.core.audioanalysis.ChapterDetector].
 */
data class Chapter(
    val mediaItemId: Long,
    val index: Int,
    /** Position of the chapter boundary in milliseconds. */
    val positionMs: Long,
    /** True for [com.exapps.velox.core.audioanalysis.ChapterDetector] output;
     *  false for sidecar `.chapters.txt` or embedded chapters. */
    val autoGenerated: Boolean,
)
