package com.exapps.velox.core.audioanalysis

import com.exapps.velox.core.domain.audio.Chapter
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.abs
import kotlin.math.log10
import kotlin.math.sqrt

/**
 * Phase 3 / Wave 3 / Round 2 — Milestone 6: auto chapter generation.
 *
 * A second detector that runs the same RMS pipeline as
 * [SilenceDetector] but at a higher temporal resolution (50 ms
 * windows) and clusters adjacent windows whose spectrograms
 * differ above a threshold. Chapter boundaries fall at cluster
 * transitions.
 *
 * The current implementation is intentionally light: a
 * mid-track boundary fires when the RMS envelope changes by
 * more than 6 dB between two adjacent windows. This catches
 * obvious vocal / instrumental transitions in music and
 * speech / silence flips in podcasts. Heavy chapter detection
 * (speech diarisation, NLP for topic shifts) is out of scope for
 * Phase 3 and is tracked as a "Phase 4 — Intelligence v2" item.
 *
 * Per the plan, chapter detection is **experimental**: the
 * Settings toggle defaults to OFF, and the chapter results
 * surface in the existing Markers sheet with a distinct
 * `autoGenerated` flag so the user can bulk-delete them if the
 * quality is poor.
 */
@Singleton
class ChapterDetector @Inject constructor() {

    /**
     * @param pcm 16-bit signed little-endian PCM samples.
     * @param sampleRate Hz.
     * @param trackDurationMs total length. Used to suppress
     *   chapters in the first 5 s and last 5 s (the leading and
     *   trailing intros/outros often look like chapter boundaries
     *   to a naïve detector).
     * @param minChapterMs minimum spacing between chapters.
     *   Anything closer than this is merged.
     */
    fun detect(
        mediaItemId: Long,
        pcm: ByteArray,
        sampleRate: Int,
        trackDurationMs: Long,
        minChapterMs: Long = 30_000L,
    ): List<Chapter> {
        if (pcm.isEmpty() || sampleRate <= 0 || trackDurationMs <= 0) return emptyList()

        val samples = pcm.toShortLE()
        val windowSizeMs = 50
        val windowSizeSamples = (sampleRate * windowSizeMs / 1000).coerceAtLeast(1)
        val windows = computeWindows(samples, windowSizeSamples, sampleRate)

        // 1. Find the RMS-delta "breakpoints": adjacent windows
        // whose RMS differs by ≥ 6 dB.
        val breakpoints = mutableListOf<Long>()
        for (i in 1 until windows.size) {
            val dB = abs(windows[i].rmsDb - windows[i - 1].rmsDb)
            if (dB >= 6.0) {
                val ms = windows[i].startMs
                if (ms in 5_000..(trackDurationMs - 5_000)) {
                    breakpoints += ms
                }
            }
        }

        // 2. Cluster breakpoints that are within `minChapterMs`
        // of each other — keep the *first* one in each cluster.
        val chapters = mutableListOf<Chapter>()
        var index = 0
        var last = Long.MIN_VALUE
        for (bp in breakpoints) {
            if (bp - last >= minChapterMs) {
                chapters += Chapter(
                    mediaItemId = mediaItemId,
                    index = index,
                    positionMs = bp,
                    autoGenerated = true,
                )
                index++
                last = bp
            }
        }
        return chapters
    }

    private data class Window(val startSample: Int, val rmsDb: Double, val sampleRate: Int) {
        val startMs: Long get() = (startSample.toLong() * 1000L / sampleRate)
    }

    private fun computeWindows(samples: ShortArray, windowSize: Int, sampleRate: Int): List<Window> {
        val windows = mutableListOf<Window>()
        var i = 0
        while (i < samples.size) {
            val end = (i + windowSize).coerceAtMost(samples.size)
            var sumSquares = 0.0
            for (j in i until end) {
                val v = samples[j].toDouble()
                sumSquares += v * v
            }
            val count = (end - i).coerceAtLeast(1)
            val meanSquares = sumSquares / count
            val rms = sqrt(meanSquares)
            val db = if (rms <= 0.0) Double.NEGATIVE_INFINITY else 20.0 * log10(rms / Short.MAX_VALUE)
            windows += Window(startSample = i, rmsDb = db, sampleRate = sampleRate)
            i += windowSize
        }
        return windows
    }
}
