package com.exapps.velox.core.audioanalysis

import com.exapps.velox.core.common.di.ApplicationScope
import com.exapps.velox.core.data.local.dao.TrackAnalysisDao
import com.exapps.velox.core.data.local.entity.TrackChapterEntity
import com.exapps.velox.core.data.local.entity.TrackIntroOutroEntity
import com.exapps.velox.core.domain.audio.Chapter
import com.exapps.velox.core.domain.audio.IntroOutro
import com.exapps.velox.core.domain.audio.IntroOutroKind
import com.exapps.velox.core.domain.audio.TrackAnalysisService
import com.exapps.velox.core.domain.audio.TrackAnalyzer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Phase 3 / Wave 3 / Round 2 — Default implementation of the
 * [TrackAnalysisService] port. The PCM-decode + analysis runs
 * on the application scope (so the work outlives any one
 * Activity or ViewModel); the rest of the app subscribes to
 * the per-track intro/chapter flows.
 */
@Singleton
class DefaultTrackAnalysisService @Inject constructor(
    private val analyzer: TrackAnalyzer,
    private val decoder: AndroidPcmDecoder,
    private val dao: TrackAnalysisDao,
    @ApplicationScope private val appScope: CoroutineScope,
) : TrackAnalysisService {

    override fun observeIntros(mediaItemId: Long): Flow<List<IntroOutro>> =
        dao.observeIntros(mediaItemId).map { rows ->
            rows.map { row ->
                IntroOutro(
                    mediaItemId = row.mediaItemId,
                    kind = kindFromInt(row.kind),
                    startMs = row.startMs,
                    endMs = row.endMs,
                )
            }
        }

    override fun observeChapters(mediaItemId: Long): Flow<List<Chapter>> =
        dao.observeChapters(mediaItemId).map { rows ->
            rows.map { row ->
                Chapter(
                    mediaItemId = row.mediaItemId,
                    index = row.index,
                    positionMs = row.positionMs,
                    autoGenerated = row.autoGenerated,
                )
            }
        }

    override fun scheduleFirstListenAnalysis(mediaItemId: Long, mediaUri: String) {
        appScope.launch {
            val decoded = decoder.decode(mediaUri) ?: return@launch
            val result = analyzer.analyze(
                mediaItemId = mediaItemId,
                pcm = decoded.toBytes(),
                sampleRate = decoded.sampleRate,
                trackDurationMs = decoded.durationMs,
            )
            persistResults(mediaItemId, result)
        }
    }

    override fun scheduleChapterOnlyAnalysis(mediaItemId: Long, mediaUri: String) {
        appScope.launch {
            val decoded = decoder.decode(mediaUri) ?: return@launch
            val pcm = decoded.toBytes()
            // Build a result with only chapters; intros are empty.
            // Reuse the same detector pair so any future change to
            // the silence / chapter logic applies here too.
            val chapters = run {
                // Inline the chapter call rather than going
                // through the analyzer facade (which always runs
                // both detectors). The detector is package-private
                // to :core:audio-analysis, so we route through
                // the facade.
                val pcm2 = pcm
                analyzer.analyze(
                    mediaItemId = mediaItemId,
                    pcm = pcm2,
                    sampleRate = decoded.sampleRate,
                    trackDurationMs = decoded.durationMs,
                ).chapters
            }
            if (chapters.isNotEmpty()) {
                dao.upsertChapters(
                    chapters.map { chapter ->
                        TrackChapterEntity(
                            mediaItemId = chapter.mediaItemId,
                            index = chapter.index,
                            positionMs = chapter.positionMs,
                            autoGenerated = chapter.autoGenerated,
                        )
                    },
                )
            }
        }
    }

    private suspend fun persistResults(mediaItemId: Long, result: com.exapps.velox.core.domain.audio.TrackAnalysisResult) {
        if (result.intros.isNotEmpty()) {
            dao.upsertIntros(
                result.intros.map { row ->
                    TrackIntroOutroEntity(
                        mediaItemId = row.mediaItemId,
                        kind = kindToInt(row.kind),
                        startMs = row.startMs,
                        endMs = row.endMs,
                    )
                },
            )
        }
        if (result.chapters.isNotEmpty()) {
            dao.upsertChapters(
                result.chapters.map { chapter ->
                    TrackChapterEntity(
                        mediaItemId = chapter.mediaItemId,
                        index = chapter.index,
                        positionMs = chapter.positionMs,
                        autoGenerated = chapter.autoGenerated,
                    )
                },
            )
        }
    }

    override suspend fun getIntroOutro(mediaItemId: Long, kind: IntroOutroKind): IntroOutro? {
        val row = dao.getIntroOutro(mediaItemId, kindToInt(kind)) ?: return null
        return IntroOutro(
            mediaItemId = row.mediaItemId,
            kind = kind,
            startMs = row.startMs,
            endMs = row.endMs,
        )
    }

    override suspend fun clearAllAutoChapters(): Int = dao.clearAllAutoChapters()

    private fun kindToInt(kind: IntroOutroKind): Int = when (kind) {
        IntroOutroKind.INTRO -> 0
        IntroOutroKind.OUTRO -> 1
    }

    private fun kindFromInt(value: Int): IntroOutroKind = when (value) {
        0 -> IntroOutroKind.INTRO
        else -> IntroOutroKind.OUTRO
    }
}
