package com.exapps.velox.core.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.exapps.velox.core.data.local.entity.TrackChapterEntity
import com.exapps.velox.core.data.local.entity.TrackIntroOutroEntity
import kotlinx.coroutines.flow.Flow

/**
 * Phase 3 / Wave 3 / Round 2 — DAO for the audio-analysis tables.
 *
 * Both tables are append-mostly: the analyzer re-runs on the
 * first listen of a track and writes whatever it finds. The
 * primary-key `(mediaItemId, kind)` / `(mediaItemId, index)`
 * means REPLACE conflicts are the natural upsert.
 */
@Dao
interface TrackAnalysisDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertIntros(entries: List<TrackIntroOutroEntity>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertChapters(entries: List<TrackChapterEntity>)

    @Query("SELECT * FROM track_intro_outro WHERE mediaItemId = :mediaItemId")
    fun observeIntros(mediaItemId: Long): Flow<List<TrackIntroOutroEntity>>

    @Query("SELECT * FROM track_chapters WHERE mediaItemId = :mediaItemId ORDER BY `index` ASC")
    fun observeChapters(mediaItemId: Long): Flow<List<TrackChapterEntity>>

    @Query("SELECT * FROM track_intro_outro WHERE mediaItemId = :mediaItemId AND kind = :kind LIMIT 1")
    suspend fun getIntroOutro(mediaItemId: Long, kind: Int): TrackIntroOutroEntity?

    @Query("DELETE FROM track_intro_outro WHERE mediaItemId = :mediaItemId")
    suspend fun clearIntros(mediaItemId: Long)

    @Query("DELETE FROM track_chapters WHERE mediaItemId = :mediaItemId")
    suspend fun clearChapters(mediaItemId: Long)

    /**
     * Phase 3 / Wave 3 / Round 3.5e — bulk-delete all auto-detected
     * chapters across every track. Sidecar `.chapters.txt`
     * chapters are not stored in this table (they're parsed at
     * load time by [com.exapps.velox.feature.player.ChaptersLoader]),
     * so this delete only affects the auto-detected rows. Returns
     * the number of rows removed so the Settings UI can confirm.
     */
    @Query("DELETE FROM track_chapters WHERE autoGenerated = 1")
    suspend fun clearAllAutoChapters(): Int
}
